image: node:8

# Cache dependencies.
cache:
  paths:
    - node_modules/

stages:
  - test
  - lint
  - code_quality
  - deploy-gl-pages
  - deploy-heroku

# Define the desired stages.
test:
  stage: test
  script:
    - yarn install
    - yarn test

  # https://gitlab.com/gitlab-org/gitlab-ce/issues/29642
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

lint:
  stage: lint
  script:
    - yarn install
    - yarn lint

# Code quality setup.
code_quality:
  stage: code_quality
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
      --env SOURCE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

# Auto-deployment to GitLab pages.
pages:
  stage: deploy-gl-pages
  script:
    - (if [[ -z $DEPLOY_TO_GL_PAGES ]]; then echo "$DEPLOY_TO_GL_PAGES is unset. Set this value to true if you'd like to enable auto-deployment to GitLab pages."; exit 0; fi);
    - (if [[ $DEPLOY_TO_GL_PAGES = false ]]; then echo "Skipping auto-deployment to GitLab pages."; exit 0; fi);
    # https://docs.gitlab.com/ee/user/project/pages/getting_started_part_four.html#the-public-directory
    # Move the production-ready version into the `public` folder.
    - yarn run build
    - mv generated_build_folder public
    - cd public && touch .nojekyll
  artifacts:
    paths:
    - public 
  only:
  - master

# Auto-deployment to Heroku.
deploy:
  stage: deploy-heroku
  only:
    - master
  image: ruby:latest
  script:
    - (if [[ -z $HEROKU_APP_NAME ]] || [[ -z $HEROKU_API_KEY ]]; then echo "$HEROKU_APP_NAME or $HEROKU_API_KEY is unset. Set these environment variables so that enable auto-deployment to Heroku."; exit 0; fi);
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY

